### PR TITLE
Merge Dockerfile into branch 'dev'

### PR DESCRIPTION
**Pull request by br3ndonland**
When setting up the Docker container, @KonradSchieban created a branch `Konrad`. We decided to push the Dockerfile from branch `Konrad` directly to branch `master`, and to auto-build the Docker container from the branch `master` with Docker Cloud so it builds from a stable, cohesive version of the app.

Although Docker Cloud is building from `master`, it apparently runs build tests on all branches. The build tests were failing for `dev`, seen in #23 from @AbdouSeck,  simply because the Dockerfile was not present.

### CODE REVIEW

**Comment by AbdouSeck** [comment]
The Dockerfile was part of the `dev` branch when I submitted the pull request yesterday. I always make sure that before pushing any changes through `dev`, I do the following:
```
git checkout master
git pull
git checkout dev
git merge master
```
That last line did bring the Dockerfile from `master` to `dev`. So by the time I submitted my pull request, the Dockerfile was already part of the `dev` branch. @br3ndonland @KonradSchieban, would it be okay to have access to the Docker cloud logs, so just in case this happens again I know what's missing or broken?

**Comment by br3ndonland** [comment]
Thank you for clarifying @AbdouSeck . Pulling from the `master` before checking out to `dev` is a good idea. Although you have the Dockerfile in `dev` locally, it is not present in `dev` on GitHub, which seems to be why the Docker build was failing.

I could have avoided this issue by pulling from `konrad` to `dev`, then from `dev` to `master`, instead of going directly from `konrad` to `master`. Apologies for the confusion.

**Comment by br3ndonland** [comment]
@AbdouSeck I confirmed that the Docker build of the `dev` branch was successful, and merged your pull request #23 . Again, sorry for the confusion, and thanks for clarifying everything with me.

Our Docker Cloud organization is [growwithgooglema](https://cloud.docker.com/swarm/growwithgooglema), same as GitHub. If you create a Docker cloud user, @KonradSchieban and I can add you.

**Comment by br3ndonland** [comment]
Invite sent.

**Pull request merged**
